version: '1'

services:
  client:
    image: reachdarshanv/dockertest:client
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: reachdarshanv/dockertest:backend
    ports:
      - 5000:5000