apiVersion: apps/v1
kind: Deployment
metadata: 
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: reachdarshanv/dockertest:client
          ports:
            - containerPort: 3000